name: angel_range
version: 1.0.0
description: Support for handling the Range and If-Range headers using the Angel framework.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/range.git
environment:
  sdk: ">=1.19.0"
dependencies:
  angel_framework: ^1.0.0
  range_header: ^1.0.0
dev_dependencies:
  angel_diagnostics: ^1.0.0
  angel_test: ^1.0.0
  test: ^0.12.0